{% set name = "pydiverse-pipedag" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98a6258f81f616d7ffad3e4777d0aabe535dbcb8543984cc080034f9b2d8c763

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - poetry
    - pip
    - python >=3.9,<4.0
  run:
    - pyyaml >=6.0
    - attrs >=22.1.0
    - msgpack-python >=1.0.4
    - networkx >=2.8
    - packaging >=21.3
    - pandas >=1.4.3,<2.0.0
    - pynng >=0.7.1
    - python >=3.8,<4.0
    - sqlalchemy >=1.4.39,<2.0.0
    - structlog >=22.1.0
    - tomli >=2.0.1
    - typing-extensions <5,>=4.1.0
    - python-box >=6.1.0

test:
  imports:
    - pydiverse.pipedag
  commands:
    - pip check
  requires:
    - pip

about:
  home: None
  summary: A pipeline orchestration library executing tasks within one python session. It takes care of SQL table (de)materialization, caching and cache invalidation. Blob storage is supported as well for example for storing model files.
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - NMAC427
    - windiana42
