{% set name = "pydiverse-pipedag" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydiverse_pipedag-{{ version }}.tar.gz
  sha256: 3bf30ba1bcfebf205a13dcb13f2ad4c75b46f38c9320c4882b227e908582e81c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - poetry
    - pip
    - python >=3.9,<3.11
  run:
    - pyparsing >=3.0
    - click >=8.1.3,<9.0.0
    - pydot >=1.4.2
    - python >=3.9,<4.0
    - pandas >=1.4.3
    - sqlalchemy >=1.4.39
    - typing-extensions >=4.1.0,<5.0.0
    - networkx >=2.8
    - attrs >=22.1.0
    - structlog >=22.1.0
    - pynng >=0.7.1
    - msgpack-python >=1.0.4
    - packaging >=21.3
    - python-box >=6.1.0
    - pyyaml >=6.0
    - pyarrow >=11.0.0
    - cryptography >=41.0.1

test:
  imports:
    - pydiverse.pipedag
  commands:
    - pip check
  requires:
    - pip

about:
  home: None
  summary: A pipeline orchestration library executing tasks within one python session. It takes care of SQL table (de)materialization, caching and cache invalidation. Blob storage is supported as well for example for storing model files.
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - NMAC427
    - windiana42
