{% set name = "pydiverse-pipedag" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14c0f724ecf8de0730db938cde1e02cf18da073a8f6038a553188c59f2b82835

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - poetry
    - pip
    - python >=3.9,<3.11
  run:
    - python >=3.9,<4.0
    - pandas >=1.4.3
    - sqlalchemy >=1.4.39
    - typing-extensions <5,>=4.1.0
    - networkx >=2.8
    - attrs >=22.1.0
    - structlog >=22.1.0
    - tomli >=2.0.1
    - pynng >=0.7.1
    - msgpack-python >=1.0.4
    - packaging >=21.3
    - python-box >=6.1.0
    - pyyaml >=6.0
    - pyarrow >=11.0.0

test:
  imports:
    - pydiverse.pipedag
  commands:
    - pip check
  requires:
    - pip

about:
  home: None
  summary: A pipeline orchestration library executing tasks within one python session. It takes care of SQL table (de)materialization, caching and cache invalidation. Blob storage is supported as well for example for storing model files.
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - NMAC427
    - windiana42
